/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

/**
 *
 * @author Default
 */
public class Principal extends javax.swing.JFrame {
    
    CadProduto cProduto;
    AlterarProduto aProduto;
    ExcluirProduto eProduto;
    PesquisarProduto pProduto;
    CadCliente cCliente;
    AltCliente aCliente;
    Aluguel eAluga;
    Reserva eReserva;
    
    
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        Main = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pAlterar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        pCadastrar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        pConsultar = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        pExcluir = new javax.swing.JMenuItem();
        cliAlterar = new javax.swing.JMenu();
        AlterarCli = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cliCadastrar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cliConsultar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        cliExcluir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        aluguelConsultar = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setBackground(new java.awt.Color(240, 240, 240));

        jMenu1.setText("Arquivo");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Quit.png"))); // NOI18N
        jMenuItem10.setText("Sair");
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Controle de Produto");

        pAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1365472378_txt2.png"))); // NOI18N
        pAlterar.setText("Alterar");
        pAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAlterarActionPerformed(evt);
            }
        });
        jMenu2.add(pAlterar);
        jMenu2.add(jSeparator4);

        pCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1365472380_1.png"))); // NOI18N
        pCadastrar.setText("Cadastrar");
        pCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(pCadastrar);
        pCadastrar.getAccessibleContext().setAccessibleDescription("");

        jMenu2.add(jSeparator5);

        pConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1365472379_xmag.png"))); // NOI18N
        pConsultar.setText("Consultar");
        pConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(pConsultar);
        jMenu2.add(jSeparator6);

        pExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1365472374_DeleteRed.png"))); // NOI18N
        pExcluir.setText("Excluir");
        pExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pExcluirActionPerformed(evt);
            }
        });
        jMenu2.add(pExcluir);

        jMenuBar1.add(jMenu2);

        cliAlterar.setText("Controle de Cliente");

        AlterarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EditClient.png"))); // NOI18N
        AlterarCli.setText("Alterar");
        AlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarCliActionPerformed(evt);
            }
        });
        cliAlterar.add(AlterarCli);
        cliAlterar.add(jSeparator1);

        cliCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddClient.png"))); // NOI18N
        cliCadastrar.setText("Cadastrar");
        cliCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliCadastrarActionPerformed(evt);
            }
        });
        cliAlterar.add(cliCadastrar);
        cliAlterar.add(jSeparator2);

        cliConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SearchClient.png"))); // NOI18N
        cliConsultar.setText("Consultar");
        cliAlterar.add(cliConsultar);
        cliAlterar.add(jSeparator3);

        cliExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RemoveClient.png"))); // NOI18N
        cliExcluir.setText("Excluir");
        cliExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliExcluirActionPerformed(evt);
            }
        });
        cliAlterar.add(cliExcluir);

        jMenuBar1.add(cliAlterar);

        jMenu4.setText("Equipamento");

        aluguelConsultar.setText("Alugar");
        jMenu4.add(aluguelConsultar);
        jMenu4.add(jSeparator7);

        jMenuItem1.setText("Reservar");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliCadastrarActionPerformed
        cCliente = new CadCliente();
            Main.add(cCliente);
            cCliente.setVisible(true);
    }//GEN-LAST:event_cliCadastrarActionPerformed

    private void pCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCadastrarActionPerformed
        cProduto = new CadProduto();
            Main.add(cProduto);
            cProduto.setVisible(true);
    }//GEN-LAST:event_pCadastrarActionPerformed

    private void pAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAlterarActionPerformed
        aProduto = new AlterarProduto();
            Main.add(aProduto);
            aProduto.setVisible(true);
    }//GEN-LAST:event_pAlterarActionPerformed

    private void pConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pConsultarActionPerformed
        pProduto = new PesquisarProduto();
            Main.add(pProduto);
            pProduto.setVisible(true);
    }//GEN-LAST:event_pConsultarActionPerformed

    private void pExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pExcluirActionPerformed
        eProduto = new ExcluirProduto();
            Main.add(eProduto);
            eProduto.setVisible(true);
    }//GEN-LAST:event_pExcluirActionPerformed

    private void AlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarCliActionPerformed
       aCliente = new AltCliente();
            Main.add(aCliente);
            aCliente.setVisible(true);
    }//GEN-LAST:event_AlterarCliActionPerformed

    private void cliExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliExcluirActionPerformed
        //Noffa
    }//GEN-LAST:event_cliExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlterarCli;
    private javax.swing.JDesktopPane Main;
    private javax.swing.JMenuItem aluguelConsultar;
    private javax.swing.JMenu cliAlterar;
    private javax.swing.JMenuItem cliCadastrar;
    private javax.swing.JMenuItem cliConsultar;
    private javax.swing.JMenuItem cliExcluir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem pAlterar;
    private javax.swing.JMenuItem pCadastrar;
    private javax.swing.JMenuItem pConsultar;
    private javax.swing.JMenuItem pExcluir;
    // End of variables declaration//GEN-END:variables
}
